title: Autopick LoL 
author: Enrique
email: enrique.c92@hotmail.com
description: Program for one month tutorial

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  EnriqueCesena # DO NOT include the @ character, or else the build will fail!
theme: modernist
show_excerpts: true # set to false to remove excerpts on the homepage


